# -------------------------------------------------------
# Docker Compose for production
# -------------------------------------------------------
version: '3.8'

services:
  nginx:
    build: ./nginx
    ports:
      - "80:80"
      - "90:443"
    networks:
      - appnet
    depends_on:
      - app
      
  app:
    build: ./app
    hostname: application
    expose:
      - 5000
    networks:
      - appnet
    volumes:
      - ./app:/app
    depends_on:
      - db

  db:
    image: postgres:16.1-alpine
    hostname: database
    environment:
      POSTGRES_DB: dbgpoffice
      POSTGRES_USER: superadmin
      POSTGRES_PASSWORD: secretpassword
    expose:
      - 5432
    networks:
      - appnet
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/dbgpoffice.sql:/docker-entrypoint-initdb.d/dbgpoffice.sql

networks:
  appnet:

volumes:
  postgres_data:
